name: pyge-dev
channels:
  - conda-forge
dependencies:
  - pyyaml
  # dev
  - black
  - pip
  - flake8
  - coverage
  - sphinx
  - twine
  - pytest
  - pytest-runner
  - pytest-cov
  - pre-commit
  - pip:
    - pygame
