name: pyge-dev
channels:
    - conda-forge
dependencies:
    - pip
    - pillow
    - pyyaml
    - flake8
    - coverage
    - sphinx
    - twine
    - pytest
    - pytest-runner
    - pytest-cov
    - pre-commit
    - pip:
        - pygame
